name: appflowy_plugins

packages:
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  analyze:
    run: melos exec dart analyze .
    description: |
      Run `dart analyze .` in all packages.

  format:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` in all packages.

  get:
    run: melos exec -c 1 flutter pub get
    description: |
      Run `flutter pub get` in all packages.
