name: Bug Report
description: Report a bug or issue you have encountered
title: "[Bug] "
body:
  - type: textarea
    id: desc
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce
      description: What steps can we take to reproduce this behavior?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: input
    id: plugin
    attributes:
      label: Plugin
      description: What plugin does this bug affect?
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS/Platform
      description: What OS/Platform are you using?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
      description: What version(s) of the plugin do you see this bug on?
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots (or screen recordings) to help explain your problem
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additonal context about the problem here
