name: Analyze code

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - "packages/**"

  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.19.5"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v4

      - name: Setup the Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Get Flutter dependencies
        run: melos get

      - name: Check for formatting issues
        run: melos format

      - name: Run the analyzer
        run: melos analyze
